= Testing node.js applications on OpenShift / Kubernetes

Context - trying to understand how hawtio-online works and uses nginx and node.js/express on OpenShift.

Links:

* /data/sources/_testing/grgr-test-web/patternfly-webpack/readme.adoc - yarn workspaces + TS + WebPack + esbuild

Started: 2024-12-05

== Dev notes

=== Initial setup

1. Starting fresh and run `corepack use yarn` to get empty `package.json`
2. Add manually `.yarnrc.yml`:
+
----
enableGlobalCache: false
enableTelemetry: false
nodeLinker: node-modules
pnpEnableEsmLoader: false
----
3. `git commit`


=== TypeScript

Here are the levels of TS configuration:

* `webpack` + `ts-loader`
** https://www.typescriptlang.org/docs/handbook/integrating-with-build-tools.html#webpack
** https://webpack.js.org/guides/typescript/
* `webpack` + `swc-loader` (Rust-based) - 4x faster than `ts-loader`
** https://swc.rs/docs/usage/swc-loader
* `rspack` with `builtin:swc-loader` - 10x faster than `ts-loader`
** https://rspack.dev/guide/features/builtin-swc-loader
* `spact`/`swcpack` = swc without webpack
** https://swc.rs/docs/configuration/bundling

Basic usage - just with `typescript` npm package in dev dependencies

----
$(yarn bin tsc) --init
----

Let's treat the above as canonical version of `tsconfig.json`.

https://www.typescriptlang.org/tsconfig is a documentation for option. Some are obvious, but some are not.

* `module` - Sets the module system for the program. You very likely want `nodenext` for modern Node.js projects and `preserve` or `esnext` for code that will be bundled. - this is quite clear information.
* `moduleResolution` - looks like `nodenext` or `bundler` are the only good choices.

.Emitting

Generally canonical usage of `$(yarn bin tsc)` should be used only to check the types. While the actual bundler uses the (same) configuration to do its own transpiling without type checking.

Then how the `emit`, `declaration`, `outDir`, ... options work?

.Using TypeScript through loader of the bundler

We can use https://rspack.dev[rspack] which is Rust-based, webpack-compatible bundler.
Using webpack is more canonical though.


=== Testing

Just adding `jest` dev dependency and a `ts` based test gives this:

----
$ yarn test
 FAIL  src/App.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /data/sources/github.com/grgrzybek/hawtio-online-tests/packages/introspection-app/src/App.test.ts:16
    import { describe, expect, test } from "@jest/globals";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1505:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.216 s
Ran all test suites.
----

So we need jest + ts configuration.

`yarn create jest@latest` creates some template `jest.config.ts` file based on user input.
After initialization I needed `ts-node` package.
But still:

----
Details:

/data/sources/github.com/grgrzybek/hawtio-online-tests/packages/introspection-app/src/App.test.ts:16
import { describe, expect, test } from "@jest/globals";
^^^^^^
----

https://jestjs.io/docs/getting-started#via-ts-jest points to
https://kulshekhar.github.io/ts-jest/docs/getting-started/installation/#jest-config-file which mentions `yarn ts-jest config:init` which creates:

----
export default {
  testEnvironment: "node",
  transform: {
    "^.+.tsx?$": ["ts-jest",{}],
  },
}
----

And actually this was enough:
----
$ yarn test
 PASS  src/App.test.ts
  Hawtio Online Tests
    ✓ Jest infra test (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.031 s, estimated 2 s
Ran all test suites.
----
